# Generated by Django 5.2.13 on 2026-04-12 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('mood', models.CharField(choices=[('peaceful', 'Tranquilo'), ('exciting', 'Animado'), ('scary', 'Assustador'), ('sad', 'Triste'), ('confusing', 'Confuso'), ('neutral', 'Neutro')], default='neutral', max_length=20)),
                ('characters', models.JSONField(blank=True, default=list)),
                ('scenarios', models.JSONField(blank=True, default=list)),
                ('emotions', models.JSONField(blank=True, default=list)),
                ('dream_objects', models.JSONField(blank=True, default=list)),
                ('ai_summary', models.TextField(blank=True)),
                ('generated_images', models.JSONField(blank=True, default=list)),
                ('dreamed_at', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dreams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-dreamed_at'],
            },
        ),
    ]
