# Generated by Django 5.2.13 on 2026-04-13 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dream',
            name='status',
            field=models.CharField(choices=[('processing', 'Processando'), ('done', 'Concluído'), ('error', 'Erro')], default='processing', max_length=20),
        ),
    ]
